<a href="https://colab.research.google.com/github/Raziel-JKM/Linear-algebra/blob/main/Doc/Homework_%EC%A0%95%EA%B0%95%EB%AF%BC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# 1. 다음과 같은 행렬을 만드세요
'''
10 20 30 40
50 60 70 80
'''

'\n10 20 30 40\n50 60 70 80\n'

In [3]:
n = np.array([[10,20,30,40],[50,60,70,80]])
print(n)

[[10 20 30 40]
 [50 60 70 80]]


In [4]:
# 2. 다음 행렬에서 코드를 작성해주세요

m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

'''
1. 이 행렬에서 값 7 을 인덱싱한다.

2. 이 행렬에서 값 14 을 인덱싱한다.

3. 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.

4. 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.

5. 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
'''

'\n1. 이 행렬에서 값 7 을 인덱싱한다.\n\n2. 이 행렬에서 값 14 을 인덱싱한다.\n\n3. 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.\n\n4. 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.\n\n5. 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.\n'

In [5]:
m1 = m[1,2]

print(m1)

7


In [6]:
m1 = m[2,4]

print(m1)

14


In [9]:
m1 = m[1,4]

print(m1)

9


In [8]:
m1 = m[1:,2]

print(m1)

[ 7 12]


In [20]:
m1 = [m[1,2]&m[1,3]]

print(m1)

[0]


In [16]:
m1 = m[:2,3:]

print(m1)

[[3 4]
 [8 9]]


In [ ]:
# 3. 벡터 [3, 10]의 단위벡터를 구하세요

In [21]:
import numpy as np

vector=np.array([3,10])

unit_vector = vector / np.linalg.norm(vector)
print(unit_vector)

[0.28734789 0.95782629]
